WebApplication/Models/ErrorViewModel.cs
namespace WebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication/Models/ResultSearch.cs
namespace WebApplication.Models
{
    public class ResultSearch
    {
        public string id { get;set; }
        public string url { get; set; }
    }
}

WebApplication/Models/VectorRepository.cs
using System.Text;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Runtime.CompilerServices;

namespace WebApplication.Models
{
    public static class VectorRepository
    {
        private static readonly HttpClient client = new HttpClient();

        private static string version = "?api-version=2023-02-01-preview&modelVersion=latest";

        public static async Task<List<ResultSearch>> DoVectorSearch(string searchPrompt, IConfiguration conf)
        {
            var textVector = await TextEmbedding(searchPrompt, conf);

            var payload = new
            {
                vectorQueries = new[]
                {
                    new
                    {
                        kind = "vector",
                        vector = textVector,
                        fields = "contentVector",
                        k = 10
                    }
                },
                select = "id, url",
                count = true
            };

            HttpRequestMessage message = new HttpRequestMessage()
            {
                RequestUri = new Uri(conf["AzureAiSearchEndpoint"]),
                Method = HttpMethod.Post,
                Content = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json")
            };

            message.Headers.Add("api-key", conf["AzureAiSearchKey"]);

            var response = await client.SendAsync(message);
            response.EnsureSuccessStatusCode();
            var responseJson = await response.Content.ReadAsStringAsync();
            var o = JObject.Parse(responseJson);

            var res = new List<ResultSearch>();

            foreach (var result in o.GetValue("value").AsEnumerable())
            {
                res.Add(
                    new ResultSearch() { 
                        id = ((JObject)result).GetValue("id").ToString(), 
                        url = ((JObject)result).GetValue("url").ToString() 
                    }
                    );                
            }            

            return res;
        }

        private static async Task<float[]> TextEmbedding(string text, IConfiguration conf)
        {
            string vecTxtUrl = conf["AzureComputerVisionEndpoint"] + "/computervision/retrieval:vectorizeText" + version;

            HttpRequestMessage message = new HttpRequestMessage()
            {
                RequestUri = new Uri(vecTxtUrl),
                Method = HttpMethod.Post,
                Content = new StringContent(JsonConvert.SerializeObject(new { text = text }), Encoding.UTF8, "application/json")
            };
            message.Headers.Add("Ocp-Apim-Subscription-Key", conf["AzureComputerVisionKey"]);

            var response = await client.SendAsync(message);
            var responseJson = await response.Content.ReadAsStringAsync();
            var responseObj = JsonConvert.DeserializeObject<dynamic>(responseJson);
            var vector = responseObj.vector.ToObject<float[]>();

            return vector;
        }
    }
}

WebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication/Controllers/VectorSearchController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class VectorSearchController : Controller
    {
        private readonly ILogger<VectorSearchController> _logger;
        private readonly IConfiguration configuration;

        public VectorSearchController(ILogger<VectorSearchController> logger, IConfiguration configuration)
        {
            _logger = logger;
            this.configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost()]
        public async Task<IActionResult> DoSearch(string searchPrompt)
        {
            var res = await VectorRepository.DoVectorSearch(searchPrompt, this.configuration);
            return View(res);
        }
    }
}

WebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VectorSearch" asp-action="Index">Search</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication/Views/VectorSearch/DoSearch.cshtml
@model List<ResultSearch>
@{
    ViewData["Title"] = "Vector Search";
}

@using (Html.BeginForm("DoSearch", "VectorSearch", FormMethod.Post))
{       
    @Html.TextBox("searchPrompt", "")
    <input type="submit" value="Search" />
}

<div id="results">
@if(this.Model != null)
{
    @foreach(var r in this.Model)
    {
        @Html.Raw($"<img src='{r.url}' class='result'/>");
    };
}
</div>

WebApplication/Views/VectorSearch/Index.cshtml
@{
    ViewData["Title"] = "Vector Search";
}

@using (Html.BeginForm("DoSearch", "VectorSearch", FormMethod.Post))
{       
    @Html.TextBox("searchPrompt", "")
    <input type="submit" value="Search" />
}